export const SERVER_URL = process.env.NEXT_PUBLIC_API_SERVER_URL
export const KAKAO_API_KEY = process.env.NEXT_PUBLIC_API_KAKAO_API_KEY
export const TOKEN_REFRESH_BUFFER = Number(process.env.NEXT_PUBLIC_TOKEN_REFRESH_BUFFER)
