name: fienmee Deploy to Dev

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    needs: cache-and-install
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Dev Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/dev
            docker compose -f docker-compose.yml pull
            docker compose -f docker-compose.yml down
            docker compose -f docker-compose.yml up -d
            docker system prune
