name: fienmee Deploy to Prod

on:
  push:
    branches:
      - main

jobs:
  deploy:
    needs: cache-and-install
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Prod Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/production
            docker compose -f docker-compose.yml pull
            docker compose -f docker-compose.yml up -d
